"""workspace-workshop workspace — workspace-workshop workspace

Three structurally-separated KB layers under steering-docs/:
  - project-kb/  → project-specific (client IP)
  - code-kb/     → codebase-specific patterns and indices (client IP)
  - domain-kb/   → project-agnostic domain know-how (DataArt IP, reusable)

MCP tools are wired explicitly per agent. Wildcards (e.g. "mcp__gitlab-da__*")
are not expanded reliably for Claude Code sub-agents, so each agent's tools=
list enumerates every MCP tool name. .mcp.json must match (see project root).

Generated by `artisyn-workspace bootstrap` from workspace-profile.yaml.
Hand-edits are preserved on re-run (hash-tracked via .artisyn/.generated-hashes.json).
Re-run `artisyn-workspace bootstrap` (with --force-workspace-py to overwrite).
"""

REPO_DISCOVERY = 'src_scan'
REPO_DISCOVERY_PATH = '../src'

from artisyn_catalog_schema import Workspace as W, Agent, Prompt, Skill

# --- File / shell tools ---

TOOLS_READ = ["fs_read", "grep", "glob"]
TOOLS_DOC = ["fs_read", "fs_write", "grep", "glob"]
TOOLS_EDIT = ["fs_read", "fs_write", "execute_bash", "grep", "glob", "TaskUpdate"]
TOOLS_LEAD = ["fs_read", "grep", "glob",
              "use_subagent", "Agent",
              "TaskCreate", "TaskGet", "TaskList", "TaskUpdate"]
TOOLS_MANAGER = TOOLS_EDIT + ["TaskCreate", "TaskGet", "TaskList"]

# --- MCP tool catalogues ---
# Wildcards aren't reliable across sub-agent invocations — list every tool name.

# GitHub read + write — repos, issues, PRs, workflows.
GITHUB_RW_TOOLS = [
    'mcp__github__create_or_update_file',
    'mcp__github__push_files',
    'mcp__github__search_repositories',
    'mcp__github__create_repository',
    'mcp__github__get_file_contents',
    'mcp__github__create_issue',
    'mcp__github__update_issue',
    'mcp__github__list_issues',
    'mcp__github__get_issue',
    'mcp__github__add_issue_comment',
    'mcp__github__create_pull_request',
    'mcp__github__update_pull_request',
    'mcp__github__list_pull_requests',
    'mcp__github__get_pull_request',
    'mcp__github__merge_pull_request',
    'mcp__github__list_pull_request_files',
    'mcp__github__create_pull_request_review',
    'mcp__github__list_branches',
    'mcp__github__create_branch',
    'mcp__github__list_commits',
    'mcp__github__get_commit',
    'mcp__github__list_workflow_runs',
    'mcp__github__get_workflow_run',
    'mcp__github__list_workflow_jobs',
    'mcp__github__search_code',
    'mcp__github__search_issues',
    'mcp__github__search_users',
]

# --- Composite tool sets ---

TOOLS_CODE = TOOLS_EDIT + GITHUB_RW_TOOLS
TOOLS_CODE_MOBILE = TOOLS_CODE
TOOLS_DEVOPS = TOOLS_EDIT + GITHUB_RW_TOOLS
TOOLS_LEAD_FULL = TOOLS_LEAD + GITHUB_RW_TOOLS

# --- Knowledge base resources ---

PROJECT_KB = [
    "file://steering-docs/project-kb/DOMAINS.md",
    "file://steering-docs/project-kb/FEATURES.md",
    "file://steering-docs/project-kb/INTEGRATIONS.md",
    "file://steering-docs/project-kb/GLOSSARY.md",
    "file://steering-docs/project-kb/PROJECT_GOALS.md",
    "file://steering-docs/project-kb/TECH_ARCHITECTURE.md",
]

DOMAIN_KB = [
    "file://steering-docs/domain-kb/GLOSSARY.md",
    "file://steering-docs/domain-kb/VENDORS.md",
]

DEVOPS_KB = [
    "file://steering-docs/code-kb/devops/CICD.md",
    "file://steering-docs/code-kb/devops/ENVIRONMENTS.md",
    "file://steering-docs/code-kb/devops/BRANCHING.md",
    "file://steering-docs/code-kb/devops/DEPLOYMENT.md",
]

workspace = W(
    name='workspace-workshop',
    description='workspace-workshop workspace',

    agents=[
        Agent(
            name='workshop-lead',
            description='Tech lead / architect and single entry point for workspace-workshop. Runs the Initiative→Epic→Story pipeline via the lead-orchestration skill: delegates decomposition to the BA, authors ADRs that gate Stories before implementation opens, and hands implementation to the dev agent. Use when decomposing an Initiative or Epic, gating an ADR, or planning cross-repo work.',
            prompt=W.prompt_ref("lead.md"),
            tools=TOOLS_LEAD_FULL, allowedTools=TOOLS_LEAD_FULL,
            resources=[*PROJECT_KB, *DOMAIN_KB],
            model='opus',
        ),
        Agent(
            name='workshop-full-stack-fastapi-template',
            description='workshop-full-stack-fastapi-template expert (full-stack-fastapi-template repo, python).',
            prompt=W.prompt_ref('python-expert.md'),
            tools=TOOLS_CODE, allowedTools=TOOLS_CODE,
            resources=[
                'file://steering-docs/code-kb/full-stack-fastapi-template/python/KNOW.md',
                'file://steering-docs/code-kb/full-stack-fastapi-template/PATTERNS.md',
                *PROJECT_KB,
                *DOMAIN_KB,
            ],
            model='sonnet',
        ),
        Agent(
            name='workshop-devops',
            description='DevOps agent for workspace-workshop. Owns CI/CD pipelines, environment topology, branching strategy, and deployment flows. Use when implementing or reviewing pipeline edits, env-config questions, rollout/rollback planning, and DB-migration ordering.',
            prompt=W.prompt_ref("devops-expert.md"),
            tools=TOOLS_DEVOPS, allowedTools=TOOLS_DEVOPS,
            resources=[*DEVOPS_KB, *PROJECT_KB],
            model="sonnet",
        ),
        Agent(
            name='workshop-domain',
            description='Domain expert for workspace-workshop. Authority on domain concepts and vendor integrations; drives extract-domain-kb and review-domain-kb. Reads domain-kb first (project-agnostic) then project-kb.',
            prompt=W.prompt_ref("domain-expert.md"),
            tools=TOOLS_DOC, allowedTools=TOOLS_DOC,
            resources=[*DOMAIN_KB, *PROJECT_KB],
            model="sonnet",
        ),
        Agent(
            name='artisyn-ws-setup',
            description="Artisyn Delivery Workspace setup helper. NOT a project manager — this agent does not track tickets, run standups, or own delivery. It runs phase-2 content refinement after `artisyn-workspace bootstrap`: enriches workspace.py agent descriptions from each repo's README + code KB, authors steering-docs/INDEX.md, refines prompts/, regenerates .claude/agents/, runs WORKSPACE_SELFTEST.md, and marks `workspace_setup_completed` in `artisyn-workspace status`. Use once, immediately after the workspace is bootstrapped. Does not fabricate project-kb content; leaves TODO templates for the user to fill.",
            prompt=W.prompt_ref("artisyn-ws-setup.md"),
            tools=TOOLS_MANAGER, allowedTools=TOOLS_MANAGER,
            resources=[*PROJECT_KB, *DOMAIN_KB],
            model="opus",
        ),
    ],

    prompts=[
        Prompt(name=W.generated("agent-guide"), description="Auto-generated agent delegation guide"),
        Prompt(name='lead.md', description='Tech lead / orchestrator prompt'),
        Prompt(name='python-expert.md', description='python expert prompt'),
        Prompt(name='devops-expert.md', description='DevOps expert: CI/CD pipelines, environments, branching, deployments'),
        Prompt(name='domain-expert.md', description='Domain expert: terminology, supplier integrations, bounded contexts'),
        Prompt(name='domain-kb-steward.md', description='Domain KB governance role: runs review-domain-kb before domain-kb commits/handoffs'),
        Prompt(name='artisyn-ws-setup.md', description='Artisyn Delivery Workspace setup helper: phase-2 content refinement after bootstrap'),
    ],

    steering=[
        "file://steering-docs/INDEX.md",
    ],
    skills=[
        Skill(name='generic-sdlc', provider_name="skill-library-aila"),
        Skill(name='lead-orchestration', provider_name="skill-library-aila"),
        Skill(name='extract-project-kb', provider_name="skill-library-aila"),
        Skill(name='extract-domain-kb', provider_name="skill-library-aila"),
        Skill(name='review-domain-kb', provider_name="skill-library-aila"),
        Skill(name='extract-code-kb', provider_name="skill-library-aila"),
        Skill(name='decompose-initiative', provider_name="skill-library-aila"),
        Skill(name='decompose-epic', provider_name="skill-library-aila"),
        Skill(name='estimate-story', provider_name="skill-library-aila"),
        Skill(name='author-adr', provider_name="skill-library-aila"),
        Skill(name='author-story', provider_name="skill-library-aila"),
        Skill(name='author-bug', provider_name="skill-library-aila"),
        Skill(name='skill-management-aila', provider_name="skill-library-aila"),
        Skill(name='aila-catalog-sdk', provider_name="skill-library-aila"),
        Skill(name='workspace-audit', provider_name="skill-library-aila"),
        Skill(name='workspace-agents-refine', provider_name="skill-library-aila"),
        Skill(name='workshop-executor', provider_name='artisyn-skill-library'),
    ],
    skill_provider=False,
    external_links=[],
)

if __name__ == "__main__":
    workspace.run_cli()
